config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/dashboard5', to: 'owners#dashboard'

  resources :restaurants do
    resources :reservations
  end

  resources :users, only: [:new, :create]

  resources :categories, only: [:new, :create, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurant_categories
  has_many :restaurants, through: :restaurant_categories

  validates :name, presence: true, uniqueness: true


end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  validates :email, presence: true
  validates :requested_date_time, presence: true


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :users
  has_many :reservations
  has_many :restaurant_categories
  has_many :categories, through: :restaurant_categories

  validates :name, presence: true, length: {minimum: 5}
  validates :description, presence: true, uniqueness: true
  validates :phone_number, presence: true

end

app/models/restaurant_category.rb
class RestaurantCategory < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :restaurants
  has_many :reservations
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}

  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that"
      redirect_to root_path
    end
  end

  def require_creator
    access_denied unless logged_in? and (current_user.admin? or current_user == @restaurant.user)
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You can't do that."
    redirect_to root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show]
  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Categories.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Your category was created."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Your category was updated."
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  binding.pry
  before_action :require_user
  def dashboard

  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @restaurant = Restaurant.find params[:restaurant_id]
    @reservation = @restaurant.reservations.build(params.require(:reservation).permit(:requested_date_time, :email, :message))
    @reservation.user = current_user

    if @reservation.save
      ReservationMailer.reservation_notice_email(@reservation).deliver
      flash[:notice] = "Your reservation was created."
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end

  end

  def destroy
    @restaurant = Restaurant.find params[:restaurant_id]
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "Your reservation was created."
    redirect_to restaurant_path(@restaurant)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]

  def index
    @restaurants = Restaurant.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end


  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new
  end


  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    
    @restaurant.save
    redirect_to @restaurant
  end


  def edit
    @restaurant = Restaurant.find(params[:id])
  end


  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end


  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :phone_number, :photo, :remote_photo_url, category_ids: [])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      # flash[:error] = "There is something wrong."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def display_datetime(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end


end

app/views/categories/_category.html.erb
<span class ="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<div class = 'well'>
<%=form_for @category do |c| %>
  <div class = 'control group'>
    <%= c.label :name %>
    <%= c.text_field :name %>
  </div>
    <br/>
    <%=c.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>
<% end %>

app/views/categories/new.html.erb
<h4>Create a category</h4>
<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% header = link_to('All Restaurants', restaurants_path) + " &raquo;  #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.restaurants.each do |restaurant| %>
  <%= render 'restaurants/restaurant', restaurant:restaurant %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul id="nav">
  <li><%= link_to 'Our Restaurants', root_path %></li>
  <% if logged_in? %>
    <li><%= link_to 'New Restaurant', new_restaurant_path %></li>
      <li>  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class = 'caret'></span>
    <% end %>
    <ul class = 'dropdown-menu'>
      <% Category.all.each do |category| %>
        <li>
          <%= link_to category.name, category_path(category)%>
      <% end %>
    </ul>
    <li><%= link_to 'Log Out', logout_path %></li>
  <% end %>
  <% unless logged_in? %>
  <li><%= link_to 'Register', new_user_path %></li>
  <li><%= link_to 'Log In', login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservester2</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class = "navbar">
        <div class = "navbar-inner">
          <div class = "container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/owners/_dashboard.html.erb
<% current_user.restaurants.each do |restaurant| %>
    <%= render '/restaurants/restaurant', restaurant: restaurant %>
<% end %>

app/views/restaurants/_form.html.erb
<div class = 'well'>
  <%= form_for @restaurant do |f| %>
  <%= render 'shared/errors', obj: @restaurant %>

    <div class = 'control group'>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class = 'control group'>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>

    <div class = 'control group'>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </div>

    <div class = 'control group'>
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
  </br>
    <div class = 'control group'>
      <%= f.file_field :photo %>
    </div>

    <div class = 'control group'>
      <%= f.label :remote_photo_url, "... or Photo URL" =%><br>
      <%= f.text_field :remote_photo_url =%>
    </div>

    <div class = 'control group'>
      <%= f.label "Categories "%><br>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|%>
        <% cb.label(class:"checkbox inline"){cb.check_box(class:"checkbox") + cb.text}%>
      <% end %>
    </div>

    <div class = 'control group'>
      <%= f.submit(@restaurant.new_record? ? 'Submit Restaurant' : 'Edit Restaurant') %>
    </div>

  <% end %>
  <p>
</div>

app/views/restaurants/_restaurant.html.erb
<div class = "row">
  <div class = "column">
        <%=image_tag restaurant.photo_url(:thumb).to_s %>
  </div>
  <div class = "column">
        <%= render restaurant.categories %>
        <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
        <small><%= restaurant.address %></small>
        <p><%= restaurant.description %></p>
        <p>
        <span class = 'quiet'>posted by</span>
        <small>at <%= display_datetime(restaurant.created_at) %></small>
        </p>
   </div> 
</div>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>
<p>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <%= render 'restaurant', restaurant: restaurant %>
<% end %>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= render 'form' %>


<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% if logged_in? and (current_user.admin? or current_user == @restaurant.user) %>
  <%@restaurant.reload.reservations.each do |reservation| %>
    <div class="well span4">
      <em><%=reservation.requested_date_time %></em><br>
      <em><%=reservation.email %></em><br>
      <em><%=reservation.message %></em><br>
      <%= link_to 'Delete', restaurant_reservation_path(reservation.restaurant, reservation), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </div>
  <% end %>
<% end %>


<% if logged_in? and current_user == @restaurant.user%>
  <h4>Make a FREE Reservation</h4>
  <%= form_for [@restaurant, @reservation] do |f| %>
  <%= render 'shared/errors', obj: @reservation %>

      <div class = 'control group'>
        <%= f.datetime_select :requested_date_time, class: "reservation_requested_date_time", label: "Please pick a day and time" %>
      </div>

      <div class = 'control group'>
        <%= f.label :email %><br>
        <%= f.email_field :email %>
      </div>

      <div class = 'control group'>
        <%= f.label :message %><br>
        <%= f.text_field :message %>
      </div>

      <%= f.submit "Make Reservation", class: "btn btn-primary" %>
  <% end %>
<% end %>

<br>
<p><%=image_tag @restaurant.photo_url(:masthead).to_s %></p>

<div class="well">
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>
</div>
<p>
<%= link_to 'Back', restaurants_path %>
<% if logged_in? and (current_user.admin? or current_user == @restaurant.user)%>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: {confirm: 'Are you sure?'} %></td>
<% end %>

app/views/shared/_content_title.html.erb
<p class = 'lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class = 'row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors.</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h4>Register an owner</h4>

<div class = 'well'>
  <%= form_for @user do |f| %>
  <%= render 'shared/errors', obj: @user %>
    <div class = 'control group'>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>
    <div class = 'control-group'>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <%= f.submit "Register", class: 'btn btn-success' %>
  <% end %>
</div>